### ISSUE TITLE
Replace Eddystone beacons with custom BLE beacon

### ISSUE THREAD

**Issue by mrstegeman** [mozilla-iot/wot#110]
This would allow us to differentiate webthings from other generic beacons. HomeKit does this as well. Their beacon includes a myriad of useful information about the device that can be read without having to connect to the device.

We already have our own DNS-SD service type, so this is just the BLE counterpart.

**Comment by mrstegeman** [comment]
Below is the BLE advertisement data for HAP (HomeKit Accessory Protocol), for reference.

---

### 6.4.2 HAP BLE 2.0 Advertisement Format
All bytes in the Advertisement Data are reserved and must not be used for any other purpose. The advertisement data must include the following fields:

#### 6.4.2.1 Flags
* Total length of three bytes.
* Length byte with value 0x02: one for the Flags AD type and one for the Flags value.
* Flags AD type, 0x01, as defined by the Bluetooth Core Specification
* The Flags value must have the LE General Discoverable Mode, bit 1, set. Since the LE General Discoverable Mode flag is set the LE Limited Discoverable Mode must not be set, as defined by the Bluetooth Core Specification

**Table 6-28** Flags Description

|Length|AD Type|Value|
|:-----|:------|:----|
|0x02|0x01|0bxxxxxx1x|

#### 6.4.2.2 Manufacturer Data
* Total length of 19 bytes.
* LEN - Length byte with a value 0x12.
* ADT - AD Type of 0xFF.
* CoID - Company Identifier code, 0x004C (Apple, Inc.), in little endian format.
* TY - 8 bits for Type, which shall be set to 0x06.
* AIL - 8 bits for Advertising Interval and Length, the 3 significant bits specify the advertising interval currently being used by the accessory, and the remaining 5 bits is the length of the remaining bytes in the manufacturer specific data which shall be set to the value 13 (i.e the lower nibble must be set to 0xD).
* SF- 8 bits for Status Flags, Bits 1-7 are reserved and shall be set to 0, Bit 0 shall reflect the value of the HAP Pairing Status Flag.
* 48-bit Device ID (Device ID (page 36)) of the accessory.
* ACID - 16-bit little endian unsigned Accessory Category Identifier,which indicates the category that best describes the primary function of the accessory. This must have a range of 1-65535. This must take one of the values defined in the Table 12-3 (page 254). The Category Identifier must not change except during a firmware update.
* GSN - 16-bit little endian unsigned Global State Number, which represents a change in the value of any of the characteristics that supports Disconnected Events (page 133). The state number must increment only once for multiple characteristic value changes while in a connected state or while in disconnected state until the accessory state changes again from connected to disconnected or disconnected to connected. This value must have a range of 1-65535 and wrap to 1 when it overflows. This value must persist across reboots, power cycles, etc. This value must be reset back to 1 when factory reset or a firmware update occurs on the accessory.
* CN - 8 bits for Configuration Number, with a default starting value of 1. Accessories must increment the config number after a firmware update. This value must have a range of 1-255 and wrap to 1 when it overflows. This value must persist across reboots, power cycles and firmware updates.
* CV - 8 bit little endian Compatible Version, this value shall be set to 0x02 for this version of the HAP BLE.

**Table 6-29** Manufacturer Specific Data

|Length|AD Type|Company ID|Type|AIL|SF|48-bit Device ID|
|:-----|:------|:---------|:---|:--|:-|:---------------|
|0x12|0xFF|0x4C 0x00|0x06|0xXX|0x00/0x01|0xXX 0xXX 0xXX 0xXX 0xXX 0xXX|

**Table 6-30** Manufacturer Specific Data - continued

|ACID|GSN|CN|CV|
|:---|:--|:-|:-|
|0xXX 0xXX|0xXX 0xXX|0xXX|0x02|

**Table 6-31** Advertising Intervals

|Value|Advertising Interval|
|:----|:-------------------|
|0x2D|10-25 ms|
|0x4D|26-100 ms|
|0x6D|101-300 ms|
|0x8D|301-500 ms|
|0xAD|501-1250 ms|
|0xCD|1251-2500 ms|
|0xED|> 2500 ms|

**Table 6-32** HAP Pairing Status Flag

|Value|Description|
|:----|:----------|
|0b0|The accessory has been paired with a controllers.|
|0b1|The accessory has not been paired with any controllers.|

#### 6.4.2.3 Local Name
* Length byte that corresponds to the total length of the local name plus the Local Name AD type.
* Local Name AD type, 0x09 or 0x08, as defined by the Bluetooth Core Specification.
The Advertisement data shall contain either the 'Shortened Local Name' or the 'Complete Local Name' If the complete local name can be included in the Advertisement data, the AD type of 0x09 (Complete Local Name) must be used, else the AD type of of 0x08 (Shortened Local Name) must be used with the name truncated to fit in the advertisement data. When the advertisement includes the shortened local name the accessory should include the complete local name in the Scan Response.
 
**Table 6-33** Local Name

|Length|AD Type|Value|
|:-----|:------|:----|
|0xXX|0x08/0x09|0xXX 0xXX ... 0xXX|

**Comment by mrstegeman** [comment]
References #75

**Comment by benfrancis** [comment]
If we did this, I think it we should try and turn it into a standard for web thing URL discovery as opposed to something proprietary for our gateway implementation. The question is whether this would be an extension of Eddystone, or something else. And whether it could be standardised via the W3C as part of the Web of Things, or would need to be done separately or through another standards body.

I bet @scottjenson has some ideas, and @phoddie has similarly proposed adding more metadata to mDNS broadcasts.

My main concern would be how much this duplicates the Thing Description itself, and what happens if the two (or three) get out of sync. Currently both Bluetooth beacons and mDNS broadcasts are used as a URL discovery mechanism, then the web layer takes over the rest. I quite like that to be honest, but I can see the attraction of including more metadata in the broadcasts themselves.

**Comment by mrstegeman** [comment]
@benfrancis I absolutely agree that this should not be proprietary to our implementation. Rather, the webthing mDNS service, and this new beacon type, should both be standardized as part of (or as an extension of) the WoT.

Right now, additional metadata in the broadcast may indeed be a duplication. However, when things start being protected by security mechanisms, such that the Thing Description cannot be read without first authenticating with the device, it makes sense to have some basic information in the broadcast. For example, with HomeKit devices, this is how we're able to classify devices as basic thing types before actually pairing with them.

While additional metadata is not necessary at this time, having our own, separate broadcast type allows us to add it in the future without having to change the fundamental broadcast type.

**Comment by mrstegeman** [comment]
We've now stopped supporting Eddystone beacons, as they're no longer supported by any major OS.
