### ISSUE TITLE
Thing icons

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/wot#126]
I have some IKEA bulbs and some Philip's bulbs and when I rename them to "kitchen" and "living room" so that speech control works, then I forget which brand of device I'm controlling. Similar to smart plugs -- I have several brands. And now I'm experimenting with IoT developer boards, some that come with onboard sensors and actuators that can become custom "things". They all look the same from an icon and control standpoint, even though one dev board is from Nordic, one from Microchip, one from STM, one from TI, etc. I'd like to know which is which.

If a thing has "branding" information I'd like it to show up when I drill down to the page displayed when I click on the splat bubble. 

Take for example an IKEA dimmable bulb. The splat page could show 3 spokes off the main bulb icon (instead of current first two in this list): 
* on/off toggle
* level control
* brand icon (IKEA logo and maybe even the bulb model or whatever detail is possible in a small form factor to better define the device)

**Comment by mrstegeman** [comment]
I'm going to close this. I see no reason to include UI-specific bits in a machine-readable thing description.

What makes more sense is to include a top-level metadata section which could include things like:
* Manufacturer
* Model
* Software version

With that information, any UI could pick specific icons as necessary.
