### ISSUE TITLE
[Question] Things Firmware Update

### ISSUE THREAD

**Issue by ekawahyu** [mozilla-iot/wot#130]
I am wondering if anyone can share a light on how to deliver firmware update within the framework of WoT, targeted to each individual device that needs to. I might have missed reading it from the spec, but if it does not exist, I thought it would be something important to have in it in order to keep all devices updated. Potentially, the Mozilla IoT Gateway can send alerts when any firmware update is available for the Things attached to it.

**Comment by mrstegeman** [comment]
Related: mozilla-iot/gateway#791

**Comment by ekawahyu** [comment]
Thanks for reference to it!
