### ISSUE TITLE
Include human-readable label in Property resource

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/wot#140]
I'm working on a voice control add-on.

When I ask the virtual leak sensor what it's state is, the api will answer only with `False`.

To turn this into a human readable response, I have to create a look-up table. _if it's a leak sensor and the response is `False`, say 'dry'_, etc

Wouldn't it be an idea to also return a human readable value through the api?
- It would be less repeated code created by add-on builders.
- It would allow add-ons to still respond with the correct state even as new capabilities are introduced in the Gateway, yet before the add-on is updated to reflect those.

**Comment by benfrancis** [comment]
@flatsiedatsie I think you're already doing the right thing by having the client generate a meaningful response to the user based on the semantic annotations already in the Thing Description.

The API is not a UI, it just contains some hints to the client as to the semantic meaning of a given operation.
