### ISSUE TITLE
More descriptive license

### ISSUE THREAD

**Issue by jtc42** [mozilla-iot/wot#150]
It would be great to have a more descriptive license in this repository. We’d like to use this spec as a starting point for a Web Things implementation, but it’s unclear if we are able to do so, and if we are, under what restrictions.

Extra license information would be wonderful.

**Comment by mrstegeman** [comment]
@jtc42 This was developed alongside the [W3C WoT Thing Description spec](https://github.com/w3c/wot-thing-description), which is subject to the [W3C Software and Document License](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document).

@disquisitioner @benfrancis What are your thoughts on this? Should our version have the same license?

**Comment by benfrancis** [comment]
@mrstegeman Yes the [W3C Document License](https://www.w3.org/Consortium/Legal/2015/doc-license) seems like an obvious choice given this document was originally intended as a W3C member submission, which [have to be licensed under that license](https://www.w3.org/2005/10/Process-20051014/submission.html#SubmissionReqs).

Note that under the W3C Document License Mozilla remains the copyright holder but they grant "Permission to copy, and distribute the contents of [the] document... in any medium for any purpose and without fee or royalty".

**Comment by jtc42** [comment]
Thanks for the quick fix! Much appreciated.
