### ISSUE TITLE
@type should be at top level of action

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/wot#153]
In [Example 8](https://iot.mozilla.org/wot/#example-8-action-object) the `"@type": "FadeAction"` should really be at the top level of the Action object rather than inside the input member, because the annotation applies to the action object and not the input. If there was an output member as well it would not have a separate `@type`.

Not sure what Mozilla WebThings implementations actually do here...

**Comment by benfrancis** [comment]
Thanks @mrstegeman ! I assume that this reflects what WebThings actually exposes?

**Comment by mrstegeman** [comment]
Yes, it was just a textual issue in this one example.
