### ISSUE TITLE
writable properties

### ISSUE THREAD

**Issue by donaldpipowitch** [mozilla-iot/wot#38]
Hi *,

I wonder if it is possible to see or check, if a property is writeable or not before sending the actual PUT request?

> Some property resources may be read only and some may be writable. ([src](https://github.com/mozilla-iot/wot/blob/gh-pages/index.html#L214))

**Comment by benfrancis** [comment]
Not currently, but I think @dhylands previously suggested adding a "writable" property to thing property objects.

My question was whether that should be part of the Thing Description or defined by some other mechanism. One issue is that whether a property is writable or not may depend on which user/consumer of the API is asking. Some users may be allowed to write a property and some users may not.

I haven't yet come up with a better mechanism though, so maybe the Thing Description is the right place for this.

Of course the other question is whether to call it "writable" or "writeable" ;)

**Comment by donaldpipowitch** [comment]
> Of course the other question is whether to call it "writable" or "writeable" ;)

😄 

> One issue is that whether a property is writable or not may depend on which user/consumer of the API is asking.

Is there some kind of personalized response already? E.g. can it be user/consumer specific if a property is _readable_, too?

**Comment by benfrancis** [comment]
> Is there some kind of personalized response already? E.g. can it be user/consumer specific if a property is readable, too?

Sure, properties are exposed as resources in a REST API. Any web resource can have authentication and granular authorisation applied to it. Currently properties are readable and writeable by any authenticated user (who provides a JSON Web Token in the request), and completely inaccessible by an unauthenticated user. Currently all logged in users have equal access to all properties, but I can imagine this changing in more complex cases.

**Comment by dhylands** [comment]
I think that there are 2 very distinct concepts here.
1 - Whether a property is physically writable/modifiable or not.
2 - Whether a user is authorized to modify a modifiable property.

I that that 1 belongs in the thing description and the 2 doesn't.

Some examples of read-only properties:
- voltage level of battery
- firmware version installed on the end-device

Some example of a modifiable property:
- on/off for a switch
- setting a setpoint on a thermostat

I'm also pretty sure that there are write-only properties. The only one I can think of off the top of my head is the encryption key for a ZigBee controller. I seem to recall seeing some on ZWave devices, but I'll need to dig a bit more.

**Comment by benfrancis** [comment]
> I think that there are 2 very distinct concepts here.

Good point.

> I'm also pretty sure that there are write-only properties

In which case, would a "writable" property not be enough?

**Comment by dhylands** [comment]
In the zwave XML file (zwcfg_0xHHHHHHHH.xml) which contains a snapshot of the devices on your network, I see that there are `read_only` and `write_only` booleans for each value.

In my current XML file, the only thing I've found with `write_only="true"` are button values, which makes sense. These act like a trigger event.

So I think we either need 2 fields, like read_only=true/false, and write_only=true/false or a combined field which encapulates R, W, and RW. I don't think that non-readable, non-wirtable values are particularly useful.

**Comment by igilham** [comment]
I think I'd prefer some sort of enum to a clumsy pair of booleans.

It may be worth thinking about whether a writeable property or an action and a read-only property is more appropriate for some values. The basic onOffSwitch as already defined requires a writeable `on` property and exposes a `toggle` action for when we don't care what the current state is. It would be equally valid to make the property read-only and expose a `set` action or a pair of actions to `set` and `reset` the value. What's the longer-term vision for API design when more complex devices with multiple capabilities start to appear?

**Comment by dhylands** [comment]
My vision is that we wind up with some type of data driven mechanism where there would be some type of matching criteria. It probably needs to be slightly different for each protocol. For ZWave, a multi-sensor just winds up having multiple category classes. I was envisioning that a particular command class, or set of command classes would wind up causing a set of properties/actions/events to be created.

**Comment by dhylands** [comment]
Another example of a write-only property would be the contents of an LCD screen using one of the 2x16 (or similar) type LCDs. You can write data to them, but you can't read them back to see that they contain. Obviously you could cache the results.

Another example would be X-10 devices. You can turn them on or off but you can't query them to determine there state, And since they can be controlled by other remotes and stuff, even caching won't help. I could turn a light on using the gateway and then turn it off using a remote, and there is no way for the gateway to know whether its on or off.

**Comment by DurandA** [comment]
Do you plan do make it explicit in the [Property](https://iot.mozilla.org/wot/#property-object) of the Thing Description similarly to the [W3C Property](https://w3c.github.io/wot-thing-description/#property)? Or do you plan to use protocol API features like HTTP OPTIONS for the REST API?

**Comment by mrstegeman** [comment]
I believe we intend to make it explicit in the property description.

**Comment by dhylands** [comment]
Sensor devices also need read-only properties. For example, a temperature reported by a temperature sensor should not be modifiable in the UI.

**Comment by mrstegeman** [comment]
The webthing-{java,node,python} libraries all support read-only properties internally, i.e. when you send them a PUT request, a 403 response will be returned. However, there is still no way to know it's read-only from the thing description.

**Comment by benfrancis** [comment]
Note: The W3C spec still hasn't quite settled on how to do this. There are examples using both a "writable" attribute and a "readOnly" attribute. I think part of the issue is whether terms are re-used from JSON Schema, which doesn't necessarily have the most sensible defaults for our use case.

**Comment by benfrancis** [comment]
It appears the latest W3C Editor's Draft has stabilised on `writable`. We should support that.

**Comment by mrstegeman** [comment]
Yay! I'm ready for it.

**Comment by mrstegeman** [comment]
See also: https://github.com/w3c/wot-thing-description/issues/209
