### ISSUE TITLE
Add support for multiLevelSwitch

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/wot#43]
I'd like to propose that we add support for a multiLevelSwitch. This would have the following properties:
- on (as per onOffSwitch)
- level of type "percentage" would be a number in the range 0 to 100.

This would allow us to support dimmable modules under both ZigBee and ZWave.

**Comment by dhylands** [comment]
Refining

level should be of type 'number' with a unit of '%', min of 0, and max of 100

% is considered to a dimensionless unit.
See: https://www.bipm.org/en/publications/si-brochure/section5-3-7.html

**Comment by benfrancis** [comment]
Closed by https://github.com/mozilla-iot/wot/pull/47

Please file a bug if you think "percent" as the unit is wrong, but it seems strange to use a symbol for percentage when everything else uses words.
