### ISSUE TITLE
need web thing type for smart locks

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/wot#53]
Here is an example API from lockitron: https://api.lockitron.com/

We need a web thing type definition for a smart lock. Or maybe even a couple different types of smart locks. For example, those that click to temporarily unlock and then fall back to a locked state, or those that toggle between locked and unlocked states. It seems somewhat analogous to a pushbutton that you have to continue to press for it to remain active versus a switch that is set to either on or off.

For existing smart locks, we'll need an [adapter](https://github.com/mozilla-iot/example-adapter) running on the [Things Gateway](https://github.com/mozilla-iot/wiki/wiki/Adapter-IPC) to accommodate them. For new locks, we'd like the smart lock industry to move toward WoT standardization.

**Comment by mrstegeman** [comment]
Duplicates mozilla-iot/schemas#11

**Comment by raidnet-ms** [comment]
What about using the IOT gateway ACL to enable users to open the door?
