### ISSUE TITLE
Provide a link to a web interface for a Thing

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/wot#68]
As a  web thing developer I would like to provide a custom web interface for my web thing in HTML so that I can provide a more intuitive interface for a complex thing.

Could add a link to the `links` member which points to an HTML UI.

e.g. 

```
  {
    "rel": "alternate",
    "mediaType": "text/html",
    "href": "https://things.com/things/lamp/index.html"
  }
```

See also https://github.com/w3c/wot-thing-description/issues/109

**Comment by mrstegeman** [comment]
Fixed by #74
