### ISSUE TITLE
Should properties have a "kind"?

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/wot#8]
The "type" field currently refers to the type of the value that the property has, boolean, integer, float, etc.

I've wondering if there should also be a kind, something like wall switch versus a switched outlet. Maybe this distinction should just be at the UI and something persisted in the database rather than as a property attribute?

**Comment by benfrancis** [comment]
In our [latest internal draft](https://docs.google.com/document/d/1Cr4IGTdzwWN_UrMjwemTwXz3VmJD4X57ljZh2NaaADg/edit?usp=sharing) a Thing has a type and a Property has a type.

My current thinking is that the specification might define a base list of simple device types (a bit like ZigBee HA device types, Z-Wave device classes and Bluetooth profiles) and a [separate document](https://docs.google.com/a/mozilla.com/document/d/1oyTM3NPjQOOohTqkjfq1klHalfcEn5w9Ull0_wadbJw/edit?usp=sharing) would describe how those Thing types can be mapped onto those various protocols. But this basic list of types can be extended through additional schemas (possibly through iot.schema.org and/or using JSON Schemas identified by a URL).

Examples of a type of thing might be:
- thing (the base type with a name and description but no required properties, actions or events)
- onOffSwitch (a simple actuator device with a boolean property and perhaps a toggle action)
- onOffSensor (a simple sensor device with a boolean property)
- levelControlSwitch
- temperatureSensor
- leakSensor
- proximitySensor
- smartPlug
- thermostat
- camera
- http://acme.com/someTypeWeMadeUp.json

Properties of Things also have a name, a type, a URL and may have a unit and a description. Examples of a type of property might be:
- boolean
- number
- string
- datetime
- vector

A wall switch is a Thing which could probably be represented as a simple onOffSwitch type, a more complex type like smartPlug (e.g. which also reports power consumption), or a custom type defined by a JSON schema and identified by a URL.

Multiple Properties of a Thing might share the same primitive data type, but may be distinguished by their name and unit.

```
    {
      "name": "temperature",
      "type": "integer",
      "unit": "celsius",
      "description": "An ambient temperature sensor",
      "href": "/things/pi/temperature"
    },
    {
      "name": "humidity",
      "type": "integer",
      "unit": "percent",
      "href": "/things/pi/humidity"
    }
```

Do you think in this model a property needs a "kind", or is that covered by Thing type and Property type?

(I will try to move as much of our current internal draft over to GitHub as I can to help this conversation make more sense to anyone following along).

**Comment by dhylands** [comment]
My thinking was that "kind" would be useful for the UI. For example, I have a thermostat which has a current temperature, a threshold temperature, a humidity and a threshold humidity. The type for all of these would be "integer" (or perhaps float). But from the UI perspective, it might make sense to know the difference between the temperature properties versus the humidity properties. If they're just displayed/manipulated as numbers then it doesn't matter. But if they're displayed using graphics, then the graphic for a temperature might be totally different than the graphic for a humidity.

**Comment by benfrancis** [comment]
Yes good point, I guess that's what I imagined "name" being used for. I suppose this will become more clear when we try to implement the UI!

**Comment by benfrancis** [comment]
I think this is now covered by the capabilities system and schemas.
