### ISSUE TITLE
Define separate Property/Properties, Action/Actions and Event/Events resources

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/wot#82]
The REST API spec currently defines `Property`, `Actions` and `Events` resources but not `Properties`, `Event` and `Action`. A `Properties` URL can be provided in the top level links member and `Event` and `Action` URLs can be provided in `Event` and `Action` objects respectively.

My thinking:
* `Property` resource returns one property's value
* `Properties` resource returns all properties' values
* `Action` resource returns a list of action requests for a particular action
* `Actions` resource returns a list of action requests for all actions
* `Event` resource returns an event log for one event type
* `Events` resource returns an event log for all event types

**Comment by mrstegeman** [comment]
We're really only missing `Properties` and `Event`.

**Comment by mrstegeman** [comment]
This can probably be closed as a duplicate of #35 and #36.

**Comment by benfrancis** [comment]
Yes, and #34.
